//
// Generated file, do not edit! Created by nedtool 5.2 from NL_PDU.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __NL_PDU_M_H
#define __NL_PDU_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0502
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>NL_PDU.msg:2</tt> by nedtool.
 * <pre>
 * packet Nl_pkt
 * {
 *     int Nl_pkt_id;
 *     int Nl_pkt_type;
 * }
 * </pre>
 */
class Nl_pkt : public ::omnetpp::cPacket
{
  protected:
    int Nl_pkt_id;
    int Nl_pkt_type;

  private:
    void copy(const Nl_pkt& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Nl_pkt&);

  public:
    Nl_pkt(const char *name=nullptr, short kind=0);
    Nl_pkt(const Nl_pkt& other);
    virtual ~Nl_pkt();
    Nl_pkt& operator=(const Nl_pkt& other);
    virtual Nl_pkt *dup() const override {return new Nl_pkt(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getNl_pkt_id() const;
    virtual void setNl_pkt_id(int Nl_pkt_id);
    virtual int getNl_pkt_type() const;
    virtual void setNl_pkt_type(int Nl_pkt_type);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Nl_pkt& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Nl_pkt& obj) {obj.parsimUnpack(b);}


#endif // ifndef __NL_PDU_M_H

